language: haskell
ghc: 8.2.2
before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Configure stack to use the system GHC installation
- stack config set system-ghc --global true
- export PATH=/opt/ghc/8.2.2/bin:$PATH
addons:
    apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.2.2
script:
    - stack --no-terminal --skip-ghc-check test
