name:                roman-numbers
version:             0.1.0.0
github:              "jvcalderon/h-roman-numbers"
license:             MIT
author:              "José Vte. Calderón"
maintainer:          "jvprod@hotmail.com"
copyright:           "2018 José Vte. Calderón"

extra-source-files:
- README.md
- LICENSE

description:         Please see the README on GitHub at <https://github.com/jvcalderon/h-roman-numbers#readme>

dependencies:
- base >=4.10 && <4.11
- regex-tdfa >=1.2 && <1.3
- containers >=0.5 && <0.6
- split >=0.2 && <0.3
- hspec >=2.4 && <2.5
- QuickCheck >= 2.10 && <2.11

library:
  source-dirs:     src
  exposed-modules: RomanNumbers

tests:
  roman-numbers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roman-numbers
